### PR TITLE
#11/F1: Add Schools Fixtures

### LINKED ISSUE #26: Issue #11/F1: Create Form for Schools and Tests
# Acceptance Criteria:

- [ ] A form called `SchoolForm` is visible in the storybook accessible on the Github Pages link.

- [x] The form has all the fields that are in the database table. The form fields are labelled with user-friendly names corresponding to the database table column names.

- [x] The form has suitable validations for all fields, indicating which fields are required to be non-blank, and any validation that should be performed (e.g. on dates, time values, numeric values with restricted ranges etc.). You can use regular expressions for this, or any of the other validations features of `react-query-form`, using the `register` feature, documented here <https://www.react-hook-form.com/api/useform/register/>. 

- [x] The `SchoolForm.stories.js` file should have at least one story for a create scenario, and another for an update scenario.
      
- [x] The PR description where the code addressing this issue is submitted contains a screenshot of the new form (since this is a frontend change).

- [ ] The PR description where the code addressing this issue is submitted contains a link to the published storybook for the PR.

# Implementation Details:

- [x] Under `frontend/src/main/components/School/` there is a file called `SchoolForm`

- [x] Form fields correspond to the form fields of your database record.  They are are labelled with user-friendly names corresponding to the database table column names.

- [x] Add suitable validations for all of your fields indicating which fields are required to be non-blank, and any validation that should be performed (e.g. on dates, time values, numeric values with restricted ranges etc.). You can use regular expressions for this, or any of the other validations features of `react-query-form`, using the `register` feature, documented here <https://www.react-hook-form.com/api/useform/register/>. 
    
- [x] The form should take a prop called `initialContents` which is either undefined, or an object that has the same fields as the database table. When passed, it indicates that the form is being used to edit an existing object.  Fields are pre-populated with the values from the object.
      
- [x] The form should take prop called `submitAction` which is passed to the `handleSubmit` function returned by `useForm`

- [x] The form should take a prop called `buttonLabel` with a default value of `Create`.  The value of this prop is used as the label for the button     

- [x] Under `frontend/src/test/components/School/` create a file called `SchoolForm.test.js`

- [x] Under `frontend/src/stories/components/School/` create a file called `SchoolForm.stories.js`
      
# Notes

Reminders (all from `frontend` directory):
* To run storybook locally: `npm run storybook`.
* To run tests locally: `npm test`.
* Quickly test coverage locally: `npm run coverage`
* Check linting locally: `npx eslint --fix .`
* Check mutation coverage locally (slow): `npx stryker run`
* Check mutation coverage of single file (faster): `npx stryker run -m src/main/components/School/SchoolForm.js`

### PR DESCRIPTION
**Pull request by chelseastoner**
This PR adds fixtures for the school object

Closes #26

### CODE REVIEW

**Comment by chelseastoner** [comment]
not sure why this PR is tracking all previous commits, as I rebased. looking into it.

**Review by allychu — DISMISSED** [review]
Code looks good!

**Review by pconrad — CHANGES_REQUESTED** [review]
I'm wondering if the base of this PR should have been `main` rather than ` Chelsea-add-role-instructor` ?

**Review by allychu — DISMISSED** [review]
LGTM! Rebase and code looks good

**Review by pconrad — CHANGES_REQUESTED** [review]
There seem to be some unrelated changes in this file (changes to SecurityConfig.java).

To fix that, you could do:

```
git fetch
git checkout Chelsea-schools-fixtures
git pull origin Chelsea-schools-fixtures
git reset --soft origin/main
git status
```

At that point, you should see that the changes to SecurityConfig.java and schoolsFixtures.js show up in red.

If you then do:

```
git checkout src/main/java/edu/ucsb/cs156/organic/config/SecurityConfig.java
git status
```

It should restore SecurityConfig.java to it's former state.

You can then do a new commit for the fixtures:

```
git add frontend/src/fixtures/schoolsFixtures.js
git commit -m "your message here"
git push origin Chelsea-schools-fixtures -f
```

The `-f` is needed because you are force pushing the branch, i.e. overwriting the old history.

**Review by darylou — APPROVED** [review]
LGTM!

**Review by pconrad — APPROVED** [review]
LGTM!

**Pull request merged**
