### PR TITLE
do - Add School Entity

### LINKED ISSUE #29: Issue B1: Backend Issue: entity for schools
- [x] Entity class for schools table
- [x] Repository class for schools table
- [ ] Database migration

### PR DESCRIPTION
**Pull request by darylou**
This PR adds entity for school.

Closes #29

### CODE REVIEW

**Review by sumitgupta314 — DISMISSED** [review]
LGTM!

**Review by dayvidwang — DISMISSED** [review]
Looks good.

**Review by pconrad — CHANGES_REQUESTED** [review]
When adding an entity in this project, you also need to add the repository, and the database migrations.

Please see this guide:

https://ucsb-cs156.github.io/topics/liquibase/adding_a_table.html

**Comment by darylou** [comment]
Failing a flaky test. Waiting for other team PR's to get merged that fix this so we don't end up with conflicts.

**Pull request closed without merging**
