### PR TITLE
CourseIndexPage and tests

### LINKED ISSUE #44: F2: Course Index Page

### PR DESCRIPTION
**Pull request by shuyiwan**
-Finished CourseIndexPage and its test, get all tests passed and 100% coverage.
Screenshot 2023-11-28 at 9 53 29 PM-Stroybook link: https://ucsb-cs156-f23.github.io/proj-organic-f23-6pm-4/prs/52/storybook/?path=/story/pages-course-courseindexpage--empty
-Edited CourseTable so that both admin and instructor have the "edit" and "delete" button to operate.
image

-Dokku Link for this PR: https://proj-organic-chelseastoner-dev.dokku-08.cs.ucsb.edu

Close #44

### CODE REVIEW

**Review by darylou — DISMISSED** [review]
LGTM!

**Review by chelseastoner — APPROVED** [review]
LGTM!

**Review by allychu — APPROVED** [review]
LGTM! Good work!

**Review by pconrad — APPROVED** [review]
LGTM

**Pull request merged**
