### PR TITLE
Added Courses Tables

### LINKED ISSUE #22: Issue F1: fixtures, form, table for Courses - Table Component
- [ ] There are CourseTable components with storybook entries and tests

### PR DESCRIPTION
**Pull request by allychu**
In this PR, we added Courses Tables and the appropriate tests along with Courses Utils.

Screenshot 2023-11-27 at 11 17 00 PM

Closes #22

### CODE REVIEW

**Comment by dayvidwang** [comment]
since this is based off of Daryl's branch, retarget the PR to merge into that so that his changes don't show up as well

**Review by darylou — DISMISSED** [review]
LGTM! Like David said, change the target of the PR to my branch so that we don't see my commits. Thanks for working on this!

**Review by pconrad — DISMISSED** [review]
LGTM

**Review by darylou — APPROVED** [review]
LGTM (after my commits are gone)

**Review by pconrad — APPROVED** [review]
LGTM

**Pull request merged**
