### PR TITLE
Course Edit Page - merge into main

### PR DESCRIPTION
**Pull request by sumitgupta314**
This PR is the same as PR #51, expect it now merges onto main branch.

https://organic-qa.dokku-08.cs.ucsb.edu/

### CODE REVIEW

**Review by darylou — DISMISSED** [review]
LGTM! (This was already approved but the earlier PR got merged into a feature branch rather than main)

**Review by shuyiwan — DISMISSED** [review]
LGTM

**Review by pconrad — DISMISSED** [review]
LGTM

**Review by pconrad — DISMISSED** [review]
LGTM

**Review by pconrad — DISMISSED** [review]
LGTM

**Review by shuyiwan — DISMISSED** [review]
LGTM!

**Review by shuyiwan — APPROVED** [review]
LGTM!

**Review by pconrad — APPROVED** [review]
LGTM

**Pull request merged**
